const express = require('express');
const router = express.Router();

const init = function (app, staticPath) {
  const index = require('./web/index')
  const photo_type = require('./api/photo/photo_type')
  const photo_list = require('./api/photo/photo_list')
  const photo_view = require('./api/photo/photo_view')
  const huaban = require('./api/photo/huaban')
  const jandan = require('./api/photo/jandan')
  // 音樂
  const plist = require('./api/music/plist')
  const plist_songs = require('./api/music/plist_songs')
  const rank_list = require('./api/music/rank_list')
  const rank_list_info = require('./api/music/rank_list_info')
  const song_info = require('./api/music/song_info')
  const song_lrc = require('./api/music/song_lrc')
  const new_songs = require('./api/music/new_songs')
  const singer_classify = require('./api/music/singer_classify')
  const singer_list = require('./api/music/singer_list')
  const singer_info = require('./api/music/singer_info')
  const music_search = require('./api/music/search')
  const web_frame = require('./api/it/web_frame')
  const daily_list = require('./api/it/daily_list')
  const daily_info = require('./api/it/daily_info')
  const joke_list = require('./api/joke/joke_list')
  const joke_img = require('./api/joke/joke_img')
  const joke_photo = require('./api/joke/joke_photo')
  const news_list = require('./api/news/news_list')
  const video_list = require('./api/news/video_list')
  const news_detail = require('./api/news/news_detail')
  const job_list = require('./api/job/job_list')
  const job_info = require("./api/job/job_info");
  app.use('/', index)
  app.use('/api/photo_type', photo_type)
  app.use('/api/huaban', huaban)
  app.use('/api/photo_list', photo_list)
  app.use('/api/photo_view', photo_view)
  app.use('/api/rank_list', rank_list)
  app.use('/api/rank_list_info', rank_list_info)
  app.use('/api/song_info', song_info)
  app.use('/api/song_lrc', song_lrc)
  app.use('/api/plist', plist)
  app.use('/api/plist_songs', plist_songs)
  app.use('/api/new_songs', new_songs)
  app.use('/api/singer_classify', singer_classify)
  app.use('/api/singer_list', singer_list)
  app.use('/api/singer_info', singer_info)
  app.use('/api/music_search', music_search)
  app.use('/api/web_frame', web_frame)
  app.use('/api/daily_list', daily_list)
  app.use('/api/daily_info', daily_info)
  app.use('/api/joke_list', joke_list)
  app.use('/api/joke_img', joke_img)
  app.use('/api/joke_photo', joke_photo)
  app.use('/api/jandan', jandan)
  app.use('/api/news_list', news_list)
  app.use('/api/video_list', video_list)
  app.use('/api/news_detail', news_detail)
  app.use('/api/job_list', job_list)
  app.use("/api/job_info", job_info);
// web
  const web_daily = require('./web/daily_list')
  const web_daily_info = require('./web/daily_info')
  const web_photo = require('./web/photo')
  const web_jandan = require('./web/jandan')
  app.use('/web/daily_list', web_daily)
  app.use('/web/daily_info', web_daily_info)
  app.use('/web/photo', web_photo)
  app.use('/web/jandan', web_jandan)

  app.use(staticPath + '/web/huaban', require('./web/huaban'))
  app.use(staticPath + '/web/home', require('./web/home'))
  app.use(staticPath + '/web/web_frame', require('./web/web_frame'))

}

exports.init = init;